version: '3'

services:  
  php-apache-stretch:    
    build:
        context: ./docker/php-apache-stretch
        dockerfile: Dockerfile    
        args:
          - TZ=${TZ}
          - LOCALE=${LOCALE} 
          - WEB_UID=${WEB_UID}
          - WEB_GID=${WEB_GID}    
    working_dir: /var/www/html
    volumes:      
      - '${PROJECT_WEB_DIR}:/var/www/html'
      - './docker/php-apache-stretch/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf:ro'
      - './docker/php-apache-stretch/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini:ro'
    ports:
      - '${WEBSERVER_PORT}:80'
    links:
      - mariadb
    depends_on:
      - mariadb      
  mariadb:
    image: 'mariadb:10.4'
    environment:
      - TZ=${TZ}
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    volumes:
      - '/var/docker_persistent_storage/mysql:/var/lib/mysql'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb
    depends_on:
      - mariadb  
    environment:      
      - PMA_HOST=mariadb      
    ports:
      - '${PHPMYADMIN_PORT}:80'
    volumes:
      - /sessions
  ftp:
    image: stilliard/pure-ftpd:latest    
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=${FTP_USER_NAME}
      - FTP_USER_PASS=${FTP_USER_PASS}
      - FTP_USER_HOME=${FTP_USER_HOME}
      - FTP_USER_UID=${WEB_UID}
      - FTP_USER_GID=${WEB_GID}
      - FTP_PASSIVE_PORTS=${FTP_PASSIVE_PORT_BEGIN}:${FTP_PASSIVE_PORT_END}
      - TLS_USE_DSAPRAM=true 
    volumes:
      - '${PROJECT_WEB_DIR}:/var/www/html'
      - ./data/ftp:/etc/ssl/private
    ports:
      - '${FTP_PORT}:21'
      - '${FTP_PASSIVE_PORT_BEGIN}-${FTP_PASSIVE_PORT_END}:${FTP_PASSIVE_PORT_BEGIN}-${FTP_PASSIVE_PORT_END}'
